package day4;

//import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class CalculatorTest2 {
	
	private Calculator calculator;
	@BeforeEach
	void setUp() throws Exception {
		calculator = new Calculator();
		System.out.println("Running before each testcase");
	}
	

	@DisplayName(value = "divide two numbers negative")
	@Test
	void divide_two_number_test_with_exceptions() {
		
		Assertions.assertThrows(ArithmeticException.class,()->calculator.divide(1,3));
	}


	@AfterEach
	void tearDown() throws Exception {
		calculator = null;
		System.out.println("Running after each testcase");
	}
	
}
